# Generated by Django 5.0.6 on 2024-05-17 13:36

import users.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("senior", "Senior"),
                    ("junior", "Junior"),
                ],
                default=users.enums.Role["JUNIOR"],
                max_length=15,
            ),
        ),
    ]
